### ISSUE TITLE
Vanila

### ISSUE THREAD

**Issue by dark1umen** [karyol/More-Counterplay-Mod#9]
Hello, 1.2.0 version is vanila friendly, but higher versions are not. Could you make something with config option "disable coilhead item", to make it vanila friendly again? As it is in other mods such as "shipwindows", there is a config option to make it vanila friendly.

**Comment by pacoito123** [comment]
I could make it so the config file deactivates some of the Coilhead stuff more thoroughly, but are you sure everything works correctly in vanilla in `v1.2.0`? I know the Jester counterplay should partially work since the host doesn't send the RPC to clients telling them that the Jester has activated, but can other players actually see/place items on top of it? Also does deactivating turrets work for non-host players?

I still think everyone _should_ have the same list of mods to avoid any issues, but I can make that change if everything's working correctly.

**Comment by dark1umen** [comment]
Deactivating turrets work for non-host players (I mean visibility, clients cant kill it, if they dont have mod installed). About jester you are right, it works for host but other players dont see item on top of jester, it just goes through, but you could say where it is, so they wont touch it, and it works fine. Also you could use it as a client and it works fine exept jester stuff. In my experience people doesnt like install mods themselfs (too hard xD), but they like when somebody have mods like yours.

**Comment by pacoito123** [comment]
Unfortunately, it's not really possible to make a gameplay-centric mod like this work reliably alongside vanilla clients. It's different in the case of mods like `ShipWindows` since changing the ship model is purely cosmetic and shouldn't affect other players, so the `VanillaMode` setting just disables the additional features (i.e. ship upgrades and the button to close the shutters).

I don't think there's a vanilla way to sync scrap item positions across all clients without custom functionality, so desyncs are bound to happen (e.g. the host drops an item on top of the Jester, a client grabs it off the ground since it fell through it for them, and then the host picks it back up from the Jester, causing both players to hold the same item on their screens). Even if you specifically tell vanilla clients to avoid picking up items that are supposed to be on top of the Jester, just the possibility of them doing it, either on purpose or by accident, is not ideal. Not being able to disable turrets could also confuse vanilla clients if they try doing it and it just doesn't work.

I'd suggest looking into [installing r2modman](https://lethal.wiki/installation/installing-r2modman) and [sharing profile codes](https://lethal.wiki/installation/syncing-mods) (e.g. `01917c42-5e48-9d64-8044-f9945a52dd88`) with others so they can import the profile and have the same exact mods installed, it's pretty much designed to be as convenient as possible once you learn how to do it.
